services:
  mysql-store:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: seng_testing

  spring-boot-backend:
    image: pw-2023-seng-testing-ekatwikz:latest
    environment:
      SPRING_PROFILES_ACTIVE: mysql-docker,jwt
      MYSQL_STORENAME: mysql-store
      MYSQL_PASSWORD: test_password
      MYSQL_DB_NAME: seng_testing
    build:
      context: ../../backend
      dockerfile: Testing.Dockerfile

  # TODO: frontend tests: selenium? jest? something else? get it done.

