services:
  mysql-store:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: seng_testing
    healthcheck: # SO ftw? https://stackoverflow.com/a/54854239
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 15

  spring-boot-backend:
    image: pw-2023-seng-testing-ekatwikz:latest
    environment:
      SPRING_PROFILES_ACTIVE: mysql-docker,jwt
      MYSQL_STORENAME: mysql-store
      MYSQL_PASSWORD: test_password
      MYSQL_DB_NAME: seng_testing
    build:
      context: ../../backend
      dockerfile: Testing.Dockerfile
    volumes:
      - maven_local_repo:/root/.m2 # only affects local testing...?
    depends_on:
      mysql-store:
        condition: service_healthy

  # TODO: frontend tests: selenium? jest? something else? get it done.

volumes:
  maven_local_repo:

