services:
  mysql-store:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dev_password
      MYSQL_DATABASE: seng_dev
    volumes:
      - seng_dev_user_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 2s
      timeout: 5s
      retries: 40

  spring-boot-backend:
    image: pw-2023-seng-dev-ekatwikz:latest
    environment:
      MYSQL_DB_NAME: seng_dev
      MYSQL_PASSWORD: dev_password
      MYSQL_STORENAME: mysql-store
      SERVER_PORT: 8080
    build:
      context: ../../backend
      dockerfile: Dev.Dockerfile
    ports:
      - 8069:8080
    volumes:
      - ../../backend:/app/backend
      - maven_local_repo:/root/.m2
    depends_on:
      mysql-store:
        condition: service_healthy
    # TODO: backend healthcheck

  next-frontend:
    image: pw-2023-seng-frontend-dev-ekatwikz:latest
    environment:
      NEXT_PUBLIC_BACKEND_NETWORK_NAME: spring-boot-backend
      NEXT_PUBLIC_BACKEND_NETWORK_PORT: 8080
    build:
      context: ../../frontend
      dockerfile: Dev.Dockerfile
    ports:
      - 3069:3069
    volumes:
      - ../../frontend:/app/frontend
    depends_on:
      - spring-boot-backend

volumes:
  seng_dev_user_data:
  maven_local_repo:

