name: Repo Tests
run-name: Running Tests on ${{ github.actor }}'s ${{ github.event_name }} to ${{ github.ref_name }}
on: [push]
jobs:
  paths-filter: # Don't need to run every test job on every push... ?
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      should-test-backend: ${{ steps.filter.outputs.should-test-backend }}
      should-lint-frontend: ${{ steps.filter.outputs.should-lint-frontend }}
      docker-compose-changed: ${{ steps.filter.outputs.docker-compose-changed }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Filter Paths to Test
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          should-test-backend:
            - 'backend/**'
          should-lint-frontend:
            - 'frontend/**'
          docker-compose-changed:
            - 'docker-compose/**'
  backend-tests:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.should-test-backend == 'true' || needs.paths-filter.outputs.docker-compose-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Docker-Compose Backend Tests
        uses: isbang/compose-action@v1.4.1
        with:
          up-flags: "--build --abort-on-container-exit"
          compose-file: "./docker-compose/testing/docker-compose.yml"
  frontend-lint:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.should-lint-frontend == 'true' || needs.paths-filter.outputs.docker-compose-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint
  frontend-typecheck: # Repititive... ??
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.should-lint-frontend == 'true' || needs.paths-filter.outputs.docker-compose-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Typecheck Frontend
        working-directory: ./frontend
        run: npm run typecheck

